implib d3d9.lib d3d9.def
implib d3dx9.lib d3dx9.def
implib libEGL.lib libEGL.def
implib libGLESv2.lib libGLESv2.def
implib msimg32.lib msimg32.def
implib opencl.lib opencl.def
implib opengl32.lib opengl32.def
implib user32.lib user32.def
implib uuid.lib uuid.def
implib version.lib version.def
implib wininet.lib wininet.def
implib winmm.lib winmm.def
implib d2d1.lib d2d1.def
implib ole32.lib ole32.def
implib oleaut32.lib oleaut32.def
implib dwrite.lib dwrite.def
implib lz32.lib lz32.def
implib advapi32.lib advapi32.def